### ISSUE TITLE
Theme main color pallets not fully displayed 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/etrain#1]
The color pallets for the following options in the theme will not fully display:
Theme Color: https://prnt.sc/v54zy7
Box Shadow Color: https://prnt.sc/v5504x

**Comment by mahendrapratap4022** [comment]
Hi, It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198  hope they approve and merge it soon.
Thanks
