### ISSUE TITLE
Header color pallets not fully displaying

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/etrain#2]
The color pallets in the header for the following options is not fully displayed :
Header right button bg color : https://prnt.sc/v553hh
Header right button hover bg color : https://prnt.sc/v553nq

**Comment by mahendrapratap4022** [comment]
Hi, It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198  hope they approve and merge it soon.
Thanks
