### ISSUE TITLE
Header right button hover bg color not working as it should

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/etrain#3]
If we go to the Header tab, change only the header right button bg color and try to hover after on header right button hover bg color will not work : 
https://drive.google.com/file/d/1bxPGH7NyHozGXKIlVGRPbzANcAZRLGlH/view

**Comment by mahendrapratap4022** [comment]
Hey It is fixed in https://github.com/ColorlibHQ/etrain/pull/8 
Thanks for submitting it here.
