### ISSUE TITLE
404 error message upper letter

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/etrain#5]
In the preview mode for the 404 page we should have the message "404 Error" message with the upper letters like on the Shotgear Theme :
Etrain Theme : https://prnt.sc/v55h47
Shotgear Theme : https://prnt.sc/uw7pfi

**Comment by mahendrapratap4022** [comment]
Hi I have added this request in https://github.com/ColorlibHQ/etrain/pull/10
Thanks
